/**
 * BizimHesap B2B REST API Types
 * Source: https://apidocs.bizimhesap.com (2026-09)
 */

export type BizimhesapCurrency = 'TL' | 'USD' | 'EUR' | 'CHF' | 'GBP';

export const BIZIMHESAP_SUPPORTED_CURRENCIES: readonly string[] = [
  'TL',
  'USD',
  'EUR',
  'CHF',
  'GBP',
];

export interface BizimhesapInvoiceDates {
  invoiceDate: string; // ISO 8601
  dueDate: string; // ISO 8601
  deliveryDate?: string; // ISO 8601
}

export interface BizimhesapCustomer {
  customerId: string; // Required, deterministic key generated by KroptOS
  title: string; // Required, customer or company name
  address: string; // Required, billing address
  taxOffice?: string;
  taxNo?: string; // Tax number or TCKN
  email?: string;
  phone?: string;
}

export interface BizimhesapAmounts {
  currency: BizimhesapCurrency; // TL | USD | EUR | CHF | GBP
  gross: number;
  discount: number;
  net: number; // after discount, before tax
  tax: number;
  total: number;
}

export interface BizimhesapInvoiceDetailItem {
  productId: string; // Required, KroptOS SKU
  productName: string; // Required
  note?: string;
  barcode?: string;
  taxRate: number; // Required, VAT percentage (e.g. 20)
  quantity: number; // Required
  unitPrice: number; // Required
  grossPrice: number; // Required, quantity * unitPrice
  discount: number; // Required
  net: number; // Required, grossPrice - discount
  tax: number; // Required, net * taxRate / 100
  total: number; // Required, net + tax
}

export interface BizimhesapInvoicePayload {
  firmId: string; // Required, unique firm ID from BizimHesap
  invoiceNo?: string; // Optional, document/reference code
  invoiceType: 3 | 5; // 3 = Sales Invoice, 5 = Purchase Invoice
  note?: string;
  dates: BizimhesapInvoiceDates;
  customer: BizimhesapCustomer;
  amounts: BizimhesapAmounts;
  details: BizimhesapInvoiceDetailItem[];
}

export interface BizimhesapApiResponse {
  error: string;
  guid: string;
  url: string;
}

// Product/Inventory models (GET /api/b2b/products, /warehouses, /inventory/{depoId})
// Response fields are DOCUMENTATION_REQUIRED as per apidocs.bizimhesap.com
export interface BizimhesapProductResponse {
  [key: string]: any;
}

export interface BizimhesapWarehouseResponse {
  [key: string]: any;
}
