import { SettingDefinition } from '../../settings/interfaces/setting-definition.interface';

export const ORDER_SETTINGS_SECTIONS = [
  { id: 'general', label: 'Genel', icon: 'Cog6ToothIcon', description: 'Saat dilimi, para birimi, vergi ve temel sipariş kısıtlamaları' },
  { id: 'numbering', label: 'Numaralandırma', icon: 'NumberedListIcon', description: 'Sipariş kodu formatı, sayaç serisi ve dönem sıfırlama' },
  { id: 'flow', label: 'Akış ve Durumlar', icon: 'ArrowPathIcon', description: 'İlk durum, otomatik onay, teslimat tamamlama ve iptal kuralları' },
  { id: 'stock', label: 'Stok', icon: 'CubeIcon', description: 'Rezervasyon zamanlaması, düşme kuralları ve depo seçimi' },
  { id: 'payment', label: 'Ödeme & Kapıda Ödeme', icon: 'BanknotesIcon', description: 'Ödeme metotları, kapıda ödeme ücret ve limitleri, havale süresi' },
  { id: 'shipping', label: 'Kargo & Teslimat', icon: 'TruckIcon', description: 'Varsayılan taşıyıcı, ücretsiz kargo eşiği, desi ve kesim saati' },
  { id: 'invoice', label: 'Fatura', icon: 'DocumentTextIcon', description: 'Otomatik faturalandırma, entegratör, seri ve KDV oranları' },
  { id: 'returns', label: 'İade & Değişim', icon: 'ArrowUturnLeftIcon', description: 'İade penceresi, yasal süreler, kargo yükümlülüğü ve onay şartları' },
  { id: 'risk', label: 'Risk & Doğrulama', icon: 'ShieldExclamationIcon', description: 'SMS teyit eşikleri, günlük müşteri limitleri ve engelleme listeleri' },
  { id: 'checkout', label: 'Müşteri & Alanlar', icon: 'UserIcon', description: 'Zorunlu sepet alanları, misafir siparişi ve not ayarları' },
  { id: 'retention', label: 'Veri Saklama', icon: 'ClockIcon', description: 'Log saklama süreleri, dosya geçerlilikleri ve bildirim sessiz saatleri' },
] as const;

export const ORDER_SETTINGS_REGISTRY: SettingDefinition[] = [
  // ==================== 1. GENEL ====================
  {
    key: 'order.general.timezone',
    type: 'string',
    default: 'Europe/Istanbul',
    section: 'general',
    labelKey: 'order.general.timezone.label',
    descriptionKey: 'order.general.timezone.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'Europe/Istanbul', label: 'İstanbul (UTC+3)' },
        { value: 'UTC', label: 'UTC (UTC+0)' },
        { value: 'Europe/London', label: 'Londra (UTC+0 / UTC+1)' },
        { value: 'Europe/Berlin', label: 'Berlin / Paris (UTC+1 / UTC+2)' },
        { value: 'America/New_York', label: 'New York (UTC-5 / UTC-4)' },
      ],
    },
  },
  {
    key: 'order.general.currency',
    type: 'enum',
    default: 'TRY',
    section: 'general',
    labelKey: 'order.general.currency.label',
    descriptionKey: 'order.general.currency.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'TRY', label: '₺ Türk Lirası (TRY)' },
        { value: 'USD', label: '$ Amerikan Doları (USD)' },
        { value: 'EUR', label: '€ Euro (EUR)' },
        { value: 'GBP', label: '£ İngiliz Sterlini (GBP)' },
      ],
    },
  },
  {
    key: 'order.general.pricesIncludeTax',
    type: 'boolean',
    default: true,
    section: 'general',
    labelKey: 'order.general.pricesIncludeTax.label',
    descriptionKey: 'order.general.pricesIncludeTax.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.general.defaultLocale',
    type: 'string',
    default: 'tr-TR',
    section: 'general',
    labelKey: 'order.general.defaultLocale.label',
    descriptionKey: 'order.general.defaultLocale.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'tr-TR', label: 'Türkçe (tr-TR)' },
        { value: 'en-US', label: 'English (en-US)' },
        { value: 'de-DE', label: 'Deutsch (de-DE)' },
      ],
    },
  },
  {
    key: 'order.general.minOrderAmount',
    type: 'money',
    default: 0,
    section: 'general',
    labelKey: 'order.general.minOrderAmount.label',
    descriptionKey: 'order.general.minOrderAmount.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    unit: 'TRY',
  },
  {
    key: 'order.general.maxItemsPerOrder',
    type: 'int',
    default: 50,
    section: 'general',
    labelKey: 'order.general.maxItemsPerOrder.label',
    descriptionKey: 'order.general.maxItemsPerOrder.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 500 },
  },

  // ==================== 2. NUMARALANDIRMA ====================
  {
    key: 'order.numbering.prefix',
    type: 'string',
    default: 'KP',
    section: 'numbering',
    labelKey: 'order.numbering.prefix.label',
    descriptionKey: 'order.numbering.prefix.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },
  {
    key: 'order.numbering.suffix',
    type: 'string',
    default: '',
    section: 'numbering',
    labelKey: 'order.numbering.suffix.label',
    descriptionKey: 'order.numbering.suffix.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },
  {
    key: 'order.numbering.padding',
    type: 'int',
    default: 5,
    section: 'numbering',
    labelKey: 'order.numbering.padding.label',
    descriptionKey: 'order.numbering.padding.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 3, max: 10 },
    sensitive: true,
  },
  {
    key: 'order.numbering.pattern',
    type: 'string',
    default: '{PREFIX}-{YYYY}{MM}-{SEQ}',
    section: 'numbering',
    labelKey: 'order.numbering.pattern.label',
    descriptionKey: 'order.numbering.pattern.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },
  {
    key: 'order.numbering.resetPeriod',
    type: 'enum',
    default: 'YEARLY',
    section: 'numbering',
    labelKey: 'order.numbering.resetPeriod.label',
    descriptionKey: 'order.numbering.resetPeriod.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'NEVER', label: 'Asla Sıfırlama (Kesintisiz Seri)' },
        { value: 'YEARLY', label: 'Yıllık Sıfırlama (Her yılbaşında 1\'den başla)' },
        { value: 'MONTHLY', label: 'Aylık Sıfırlama (Her aybaşında 1\'den başla)' },
      ],
    },
    sensitive: true,
  },
  {
    key: 'order.numbering.nextSequence',
    type: 'int',
    default: 1,
    section: 'numbering',
    labelKey: 'order.numbering.nextSequence.label',
    descriptionKey: 'order.numbering.nextSequence.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1 },
    sensitive: true,
  },
  {
    key: 'order.numbering.separateMarketplaceSeries',
    type: 'boolean',
    default: false,
    section: 'numbering',
    labelKey: 'order.numbering.separateMarketplaceSeries.label',
    descriptionKey: 'order.numbering.separateMarketplaceSeries.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },

  // ==================== 3. AKIŞ VE DURUMLAR ====================
  {
    key: 'order.flow.initialStatusId',
    type: 'string',
    default: 'pending',
    section: 'flow',
    labelKey: 'order.flow.initialStatusId.label',
    descriptionKey: 'order.flow.initialStatusId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'orderStatus' },
  },
  {
    key: 'order.flow.autoConfirm',
    type: 'boolean',
    default: false,
    section: 'flow',
    labelKey: 'order.flow.autoConfirm.label',
    descriptionKey: 'order.flow.autoConfirm.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.flow.autoConfirmDelayMinutes',
    type: 'int',
    default: 15,
    section: 'flow',
    labelKey: 'order.flow.autoConfirmDelayMinutes.label',
    descriptionKey: 'order.flow.autoConfirmDelayMinutes.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0, max: 1440 },
    dependsOn: { key: 'order.flow.autoConfirm', value: true },
    unit: 'dakika',
  },
  {
    key: 'order.flow.autoCompleteAfterDeliveredDays',
    type: 'int',
    default: 14,
    section: 'flow',
    labelKey: 'order.flow.autoCompleteAfterDeliveredDays.label',
    descriptionKey: 'order.flow.autoCompleteAfterDeliveredDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 90 },
    unit: 'gün',
  },
  {
    key: 'order.flow.unpaidCancelAfterHours',
    type: 'int',
    default: 48,
    section: 'flow',
    labelKey: 'order.flow.unpaidCancelAfterHours.label',
    descriptionKey: 'order.flow.unpaidCancelAfterHours.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 720 },
    unit: 'saat',
  },
  {
    key: 'order.flow.editableUntilStatusId',
    type: 'string',
    default: 'processing',
    section: 'flow',
    labelKey: 'order.flow.editableUntilStatusId.label',
    descriptionKey: 'order.flow.editableUntilStatusId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'orderStatus' },
  },
  {
    key: 'order.flow.cancellableUntilStatusId',
    type: 'string',
    default: 'shipped',
    section: 'flow',
    labelKey: 'order.flow.cancellableUntilStatusId.label',
    descriptionKey: 'order.flow.cancellableUntilStatusId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'orderStatus' },
  },
  {
    key: 'order.flow.requireCancelReason',
    type: 'boolean',
    default: true,
    section: 'flow',
    labelKey: 'order.flow.requireCancelReason.label',
    descriptionKey: 'order.flow.requireCancelReason.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.flow.cancelReasons',
    type: 'tags',
    default: ['Müşteri Vazgeçti', 'Hatalı Sipariş', 'Stok Yetersiz', 'Fiyat Hatası', 'Teslimat Süresi Uzun'],
    section: 'flow',
    labelKey: 'order.flow.cancelReasons.label',
    descriptionKey: 'order.flow.cancelReasons.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },

  // ==================== 4. STOK ====================
  {
    key: 'order.stock.reserveOn',
    type: 'enum',
    default: 'ORDER_CREATED',
    section: 'stock',
    labelKey: 'order.stock.reserveOn.label',
    descriptionKey: 'order.stock.reserveOn.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'ORDER_CREATED', label: 'Sipariş Oluşturulduğunda' },
        { value: 'PAYMENT_RECEIVED', label: 'Ödeme Alındığında' },
        { value: 'CONFIRMED', label: 'Sipariş Onaylandığında' },
      ],
    },
  },
  {
    key: 'order.stock.deductOn',
    type: 'enum',
    default: 'CONFIRMED',
    section: 'stock',
    labelKey: 'order.stock.deductOn.label',
    descriptionKey: 'order.stock.deductOn.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'CONFIRMED', label: 'Sipariş Onaylandığında' },
        { value: 'SHIPPED', label: 'Kargoya Verildiğinde' },
      ],
    },
  },
  {
    key: 'order.stock.releaseOnCancel',
    type: 'boolean',
    default: true,
    section: 'stock',
    labelKey: 'order.stock.releaseOnCancel.label',
    descriptionKey: 'order.stock.releaseOnCancel.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.stock.allowBackorder',
    type: 'boolean',
    default: false,
    section: 'stock',
    labelKey: 'order.stock.allowBackorder.label',
    descriptionKey: 'order.stock.allowBackorder.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.stock.reservationTimeoutMinutes',
    type: 'int',
    default: 60,
    section: 'stock',
    labelKey: 'order.stock.reservationTimeoutMinutes.label',
    descriptionKey: 'order.stock.reservationTimeoutMinutes.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 5, max: 2880 },
    unit: 'dakika',
  },
  {
    key: 'order.stock.defaultWarehouseId',
    type: 'string',
    default: '',
    section: 'stock',
    labelKey: 'order.stock.defaultWarehouseId.label',
    descriptionKey: 'order.stock.defaultWarehouseId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'warehouse' },
  },
  {
    key: 'order.stock.warehouseSelection',
    type: 'enum',
    default: 'DEFAULT',
    section: 'stock',
    labelKey: 'order.stock.warehouseSelection.label',
    descriptionKey: 'order.stock.warehouseSelection.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'DEFAULT', label: 'Varsayılan Depo' },
        { value: 'NEAREST', label: 'Teslimat Adresine En Yakın Depo' },
        { value: 'PRIORITY_LIST', label: 'Öncelik Sıralamasına Göre' },
      ],
    },
  },

  // ==================== 5. ÖDEME & KAPIDA ÖDEME ====================
  {
    key: 'order.payment.enabledMethods',
    type: 'tags',
    default: ['CREDIT_CARD', 'BANK_TRANSFER', 'CASH_ON_DELIVERY'],
    section: 'payment',
    labelKey: 'order.payment.enabledMethods.label',
    descriptionKey: 'order.payment.enabledMethods.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.cod.enabled',
    type: 'boolean',
    default: true,
    section: 'payment',
    labelKey: 'order.cod.enabled.label',
    descriptionKey: 'order.cod.enabled.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.cod.fee',
    type: 'money',
    default: 35.0,
    section: 'payment',
    labelKey: 'order.cod.fee.label',
    descriptionKey: 'order.cod.fee.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    dependsOn: { key: 'order.cod.enabled', value: true },
    unit: 'TRY',
  },
  {
    key: 'order.cod.feeType',
    type: 'enum',
    default: 'FIXED',
    section: 'payment',
    labelKey: 'order.cod.feeType.label',
    descriptionKey: 'order.cod.feeType.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'FIXED', label: 'Sabit Tutar' },
        { value: 'PERCENT', label: 'Yüzdelik Oran (%)' },
      ],
    },
    dependsOn: { key: 'order.cod.enabled', value: true },
  },
  {
    key: 'order.cod.minAmount',
    type: 'money',
    default: 100.0,
    section: 'payment',
    labelKey: 'order.cod.minAmount.label',
    descriptionKey: 'order.cod.minAmount.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    dependsOn: { key: 'order.cod.enabled', value: true },
    unit: 'TRY',
  },
  {
    key: 'order.cod.maxAmount',
    type: 'money',
    default: 5000.0,
    section: 'payment',
    labelKey: 'order.cod.maxAmount.label',
    descriptionKey: 'order.cod.maxAmount.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    dependsOn: { key: 'order.cod.enabled', value: true },
    unit: 'TRY',
  },
  {
    key: 'order.cod.cashOnly',
    type: 'boolean',
    default: false,
    section: 'payment',
    labelKey: 'order.cod.cashOnly.label',
    descriptionKey: 'order.cod.cashOnly.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    dependsOn: { key: 'order.cod.enabled', value: true },
  },
  {
    key: 'order.cod.excludedCities',
    type: 'tags',
    default: [],
    section: 'payment',
    labelKey: 'order.cod.excludedCities.label',
    descriptionKey: 'order.cod.excludedCities.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    dependsOn: { key: 'order.cod.enabled', value: true },
  },
  {
    key: 'order.cod.requireConfirmationAbove',
    type: 'money',
    default: 2000.0,
    section: 'payment',
    labelKey: 'order.cod.requireConfirmationAbove.label',
    descriptionKey: 'order.cod.requireConfirmationAbove.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    dependsOn: { key: 'order.cod.enabled', value: true },
    unit: 'TRY',
  },
  {
    key: 'order.transfer.discountPercent',
    type: 'decimal',
    default: 0,
    section: 'payment',
    labelKey: 'order.transfer.discountPercent.label',
    descriptionKey: 'order.transfer.discountPercent.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0, max: 50 },
    unit: '%',
  },
  {
    key: 'order.transfer.paymentWindowHours',
    type: 'int',
    default: 48,
    section: 'payment',
    labelKey: 'order.transfer.paymentWindowHours.label',
    descriptionKey: 'order.transfer.paymentWindowHours.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 168 },
    unit: 'saat',
  },

  // ==================== 6. KARGO VE TESLİMAT ====================
  {
    key: 'order.shipping.defaultCarrierId',
    type: 'string',
    default: '',
    section: 'shipping',
    labelKey: 'order.shipping.defaultCarrierId.label',
    descriptionKey: 'order.shipping.defaultCarrierId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'carrier' },
  },
  {
    key: 'order.shipping.freeShippingThreshold',
    type: 'money',
    default: 750.0,
    section: 'shipping',
    labelKey: 'order.shipping.freeShippingThreshold.label',
    descriptionKey: 'order.shipping.freeShippingThreshold.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    unit: 'TRY',
  },
  {
    key: 'order.shipping.defaultDesi',
    type: 'decimal',
    default: 1.0,
    section: 'shipping',
    labelKey: 'order.shipping.defaultDesi.label',
    descriptionKey: 'order.shipping.defaultDesi.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0.1, max: 100 },
    unit: 'desi',
  },
  {
    key: 'order.shipping.desiCalculation',
    type: 'enum',
    default: 'MAX_OF_WEIGHT_VOLUME',
    section: 'shipping',
    labelKey: 'order.shipping.desiCalculation.label',
    descriptionKey: 'order.shipping.desiCalculation.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'MAX_OF_WEIGHT_VOLUME', label: 'Ağırlık ve Hacimden Büyük Olanı Al' },
        { value: 'WEIGHT', label: 'Yalnızca Ağırlık (kg)' },
        { value: 'VOLUME', label: 'Yalnızca Hacimsel Desi (En*Boy*Yükseklik / Bölen)' },
      ],
    },
  },
  {
    key: 'order.shipping.volumetricDivisor',
    type: 'int',
    default: 3000,
    section: 'shipping',
    labelKey: 'order.shipping.volumetricDivisor.label',
    descriptionKey: 'order.shipping.volumetricDivisor.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1000, max: 6000 },
  },
  {
    key: 'order.shipping.handlingTimeDays',
    type: 'int',
    default: 1,
    section: 'shipping',
    labelKey: 'order.shipping.handlingTimeDays.label',
    descriptionKey: 'order.shipping.handlingTimeDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0, max: 30 },
    unit: 'gün',
  },
  {
    key: 'order.shipping.cutoffTime',
    type: 'time',
    default: '16:00',
    section: 'shipping',
    labelKey: 'order.shipping.cutoffTime.label',
    descriptionKey: 'order.shipping.cutoffTime.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.shipping.autoCreateShipmentOn',
    type: 'string',
    default: 'confirmed',
    section: 'shipping',
    labelKey: 'order.shipping.autoCreateShipmentOn.label',
    descriptionKey: 'order.shipping.autoCreateShipmentOn.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'orderStatus' },
  },
  {
    key: 'order.shipping.labelFormat',
    type: 'enum',
    default: 'THERMAL_10X10',
    section: 'shipping',
    labelKey: 'order.shipping.labelFormat.label',
    descriptionKey: 'order.shipping.labelFormat.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'THERMAL_10X10', label: '10x10 cm Termal Etiket' },
        { value: 'A4', label: 'A4 Standart Kağıt' },
      ],
    },
  },

  // ==================== 7. FATURA ====================
  {
    key: 'order.invoice.autoCreateOn',
    type: 'enum',
    default: 'SHIPPED',
    section: 'invoice',
    labelKey: 'order.invoice.autoCreateOn.label',
    descriptionKey: 'order.invoice.autoCreateOn.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'NEVER', label: 'Otomatik Oluşturma (Manuel)' },
        { value: 'PAYMENT_RECEIVED', label: 'Ödeme Alındığında' },
        { value: 'CONFIRMED', label: 'Sipariş Onaylandığında' },
        { value: 'SHIPPED', label: 'Kargoya Verildiğinde' },
      ],
    },
    sensitive: true,
  },
  {
    key: 'order.invoice.provider',
    type: 'string',
    default: 'parasut',
    section: 'invoice',
    labelKey: 'order.invoice.provider.label',
    descriptionKey: 'order.invoice.provider.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'parasut', label: 'Paraşüt e-Fatura / e-Arşiv' },
        { value: 'logo', label: 'Logo Yazılım e-Fatura' },
        { value: 'bizimhesap', label: 'BizimHesap e-Fatura' },
      ],
    },
    sensitive: true,
  },
  {
    key: 'order.invoice.series',
    type: 'string',
    default: 'KRP',
    section: 'invoice',
    labelKey: 'order.invoice.series.label',
    descriptionKey: 'order.invoice.series.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },
  {
    key: 'order.invoice.defaultTaxRate',
    type: 'int',
    default: 20,
    section: 'invoice',
    labelKey: 'order.invoice.defaultTaxRate.label',
    descriptionKey: 'order.invoice.defaultTaxRate.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0, max: 100 },
    unit: '%',
    sensitive: true,
  },
  {
    key: 'order.invoice.includeShippingAsLine',
    type: 'boolean',
    default: true,
    section: 'invoice',
    labelKey: 'order.invoice.includeShippingAsLine.label',
    descriptionKey: 'order.invoice.includeShippingAsLine.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    sensitive: true,
  },
  {
    key: 'order.invoice.sendToCustomer',
    type: 'boolean',
    default: true,
    section: 'invoice',
    labelKey: 'order.invoice.sendToCustomer.label',
    descriptionKey: 'order.invoice.sendToCustomer.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.invoice.individualTaxIdPlaceholder',
    type: 'string',
    default: '11111111111',
    section: 'invoice',
    labelKey: 'order.invoice.individualTaxIdPlaceholder.label',
    descriptionKey: 'order.invoice.individualTaxIdPlaceholder.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { regex: '^[0-9]{11}$' },
    sensitive: true,
  },

  // ==================== 8. İADE VE DEĞİŞİM ====================
  {
    key: 'order.returns.enabled',
    type: 'boolean',
    default: true,
    section: 'returns',
    labelKey: 'order.returns.enabled.label',
    descriptionKey: 'order.returns.enabled.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.returns.windowDays',
    type: 'int',
    default: 14,
    section: 'returns',
    labelKey: 'order.returns.windowDays.label',
    descriptionKey: 'order.returns.windowDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 14, max: 90 }, // 14 days legal minimum for distance selling
    unit: 'gün',
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.windowStartsFrom',
    type: 'enum',
    default: 'DELIVERED',
    section: 'returns',
    labelKey: 'order.returns.windowStartsFrom.label',
    descriptionKey: 'order.returns.windowStartsFrom.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'DELIVERED', label: 'Teslim Edildiği Tarihten İtibaren' },
        { value: 'SHIPPED', label: 'Kargoya Verildiği Tarihten İtibaren' },
      ],
    },
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.reasons',
    type: 'tags',
    default: [
      'Vazgeçtim / İhtiyacım Kalmadı',
      'Beden / Boyut Uymadı',
      'Kusurlu / Bozuk Ürün',
      'Yanlış Ürün Gönderildi',
      'Beklediğim Gibi Değil',
    ],
    section: 'returns',
    labelKey: 'order.returns.reasons.label',
    descriptionKey: 'order.returns.reasons.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.requireApproval',
    type: 'boolean',
    default: true,
    section: 'returns',
    labelKey: 'order.returns.requireApproval.label',
    descriptionKey: 'order.returns.requireApproval.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.shippingPaidBy',
    type: 'enum',
    default: 'STORE',
    section: 'returns',
    labelKey: 'order.returns.shippingPaidBy.label',
    descriptionKey: 'order.returns.shippingPaidBy.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'STORE', label: 'Mağaza Karşılar (Ücretsiz İade Kodu)' },
        { value: 'CUSTOMER', label: 'Müşteri Öder' },
        { value: 'BY_REASON', label: 'Nedene Göre (Kusurluysa Mağaza, Vazgeçtiyse Müşteri)' },
      ],
    },
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.defaultReturnCarrierId',
    type: 'string',
    default: '',
    section: 'returns',
    labelKey: 'order.returns.defaultReturnCarrierId.label',
    descriptionKey: 'order.returns.defaultReturnCarrierId.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { referenceType: 'carrier' },
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.refundMethod',
    type: 'enum',
    default: 'ORIGINAL',
    section: 'returns',
    labelKey: 'order.returns.refundMethod.label',
    descriptionKey: 'order.returns.refundMethod.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: 'ORIGINAL', label: 'Orijinal Ödeme Aracına İade' },
        { value: 'STORE_CREDIT', label: 'Mağaza Bakiyesi / Hediye Çeki' },
        { value: 'CHOICE', label: 'Müşteri Tercihine Bırak' },
      ],
    },
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.returns.autoRefundOnReceived',
    type: 'boolean',
    default: false,
    section: 'returns',
    labelKey: 'order.returns.autoRefundOnReceived.label',
    descriptionKey: 'order.returns.autoRefundOnReceived.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    dependsOn: { key: 'order.returns.enabled', value: true },
  },
  {
    key: 'order.exchange.enabled',
    type: 'boolean',
    default: false,
    section: 'returns',
    labelKey: 'order.exchange.enabled.label',
    descriptionKey: 'order.exchange.enabled.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },

  // ==================== 9. RİSK VE DOĞRULAMA ====================
  {
    key: 'order.risk.requirePhoneVerificationAbove',
    type: 'money',
    default: 10000.0,
    section: 'risk',
    labelKey: 'order.risk.requirePhoneVerificationAbove.label',
    descriptionKey: 'order.risk.requirePhoneVerificationAbove.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    unit: 'TRY',
  },
  {
    key: 'order.risk.maxOrdersPerCustomerPerDay',
    type: 'int',
    default: 5,
    section: 'risk',
    labelKey: 'order.risk.maxOrdersPerCustomerPerDay.label',
    descriptionKey: 'order.risk.maxOrdersPerCustomerPerDay.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 100 },
  },
  {
    key: 'order.risk.blockedPhones',
    type: 'tags',
    default: [],
    section: 'risk',
    labelKey: 'order.risk.blockedPhones.label',
    descriptionKey: 'order.risk.blockedPhones.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.risk.blockedEmails',
    type: 'tags',
    default: [],
    section: 'risk',
    labelKey: 'order.risk.blockedEmails.label',
    descriptionKey: 'order.risk.blockedEmails.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.risk.holdIfBillingShippingDiffer',
    type: 'boolean',
    default: false,
    section: 'risk',
    labelKey: 'order.risk.holdIfBillingShippingDiffer.label',
    descriptionKey: 'order.risk.holdIfBillingShippingDiffer.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.risk.holdNewCustomerCodAbove',
    type: 'money',
    default: 1500.0,
    section: 'risk',
    labelKey: 'order.risk.holdNewCustomerCodAbove.label',
    descriptionKey: 'order.risk.holdNewCustomerCodAbove.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 0 },
    unit: 'TRY',
  },

  // ==================== 10. MÜŞTERİ VE ALANLAR ====================
  {
    key: 'order.checkout.requiredFields',
    type: 'tags',
    default: ['customerName', 'customerPhone', 'shippingAddress', 'shippingCity', 'shippingDistrict'],
    section: 'checkout',
    labelKey: 'order.checkout.requiredFields.label',
    descriptionKey: 'order.checkout.requiredFields.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.checkout.allowGuest',
    type: 'boolean',
    default: true,
    section: 'checkout',
    labelKey: 'order.checkout.allowGuest.label',
    descriptionKey: 'order.checkout.allowGuest.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.checkout.orderNoteEnabled',
    type: 'boolean',
    default: true,
    section: 'checkout',
    labelKey: 'order.checkout.orderNoteEnabled.label',
    descriptionKey: 'order.checkout.orderNoteEnabled.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.checkout.giftNoteEnabled',
    type: 'boolean',
    default: true,
    section: 'checkout',
    labelKey: 'order.checkout.giftNoteEnabled.label',
    descriptionKey: 'order.checkout.giftNoteEnabled.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.checkout.phoneFormat',
    type: 'string',
    default: '+90',
    section: 'checkout',
    labelKey: 'order.checkout.phoneFormat.label',
    descriptionKey: 'order.checkout.phoneFormat.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },

  // ==================== 11. VERİ SAKLAMA VE MODÜL VARSAYILANLARI ====================
  {
    key: 'order.retention.notificationLogDays',
    type: 'int',
    default: 180,
    section: 'retention',
    labelKey: 'order.retention.notificationLogDays.label',
    descriptionKey: 'order.retention.notificationLogDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 30, max: 730 },
    unit: 'gün',
    sensitive: true,
  },
  {
    key: 'order.retention.automationRunDays',
    type: 'int',
    default: 90,
    section: 'retention',
    labelKey: 'order.retention.automationRunDays.label',
    descriptionKey: 'order.retention.automationRunDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 14, max: 365 },
    unit: 'gün',
    sensitive: true,
  },
  {
    key: 'order.retention.exportFileDays',
    type: 'int',
    default: 7,
    section: 'retention',
    labelKey: 'order.retention.exportFileDays.label',
    descriptionKey: 'order.retention.exportFileDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 90 },
    unit: 'gün',
    sensitive: true,
  },
  {
    key: 'order.retention.importFileDays',
    type: 'int',
    default: 30,
    section: 'retention',
    labelKey: 'order.retention.importFileDays.label',
    descriptionKey: 'order.retention.importFileDays.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 7, max: 180 },
    unit: 'gün',
    sensitive: true,
  },
  {
    key: 'order.import.rollbackHours',
    type: 'int',
    default: 24,
    section: 'retention',
    labelKey: 'order.import.rollbackHours.label',
    descriptionKey: 'order.import.rollbackHours.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 72 },
    unit: 'saat',
    sensitive: true,
  },
  {
    key: 'order.export.maxRangeMonths',
    type: 'int',
    default: 12,
    section: 'retention',
    labelKey: 'order.export.maxRangeMonths.label',
    descriptionKey: 'order.export.maxRangeMonths.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: { min: 1, max: 60 },
    unit: 'ay',
    sensitive: true,
  },
  {
    key: 'order.export.defaultDelimiter',
    type: 'enum',
    default: ';',
    section: 'retention',
    labelKey: 'order.export.defaultDelimiter.label',
    descriptionKey: 'order.export.defaultDelimiter.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
    validation: {
      options: [
        { value: ';', label: 'Noktalı Virgül (;)' },
        { value: ',', label: 'Virgül (,)' },
      ],
    },
  },
  {
    key: 'order.notifications.defaultSenderName',
    type: 'string',
    default: 'KroptOS',
    section: 'retention',
    labelKey: 'order.notifications.defaultSenderName.label',
    descriptionKey: 'order.notifications.defaultSenderName.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.notifications.quietHoursStart',
    type: 'time',
    default: '22:00',
    section: 'retention',
    labelKey: 'order.notifications.quietHoursStart.label',
    descriptionKey: 'order.notifications.quietHoursStart.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
  {
    key: 'order.notifications.quietHoursEnd',
    type: 'time',
    default: '08:00',
    section: 'retention',
    labelKey: 'order.notifications.quietHoursEnd.label',
    descriptionKey: 'order.notifications.quietHoursEnd.desc',
    scopes: ['AGENCY', 'CLIENT', 'STORE'],
  },
];
